#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-sna
Version  : 2.7.1
Release  : 49
URL      : https://cran.r-project.org/src/contrib/sna_2.7-1.tar.gz
Source0  : https://cran.r-project.org/src/contrib/sna_2.7-1.tar.gz
Summary  : Tools for Social Network Analysis
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: R-sna-lib = %{version}-%{release}
Requires: R-sna-license = %{version}-%{release}
Requires: R-network
Requires: R-statnet.common
BuildRequires : R-network
BuildRequires : R-statnet.common
BuildRequires : buildreq-R

%description
No detailed description available

%package lib
Summary: lib components for the R-sna package.
Group: Libraries
Requires: R-sna-license = %{version}-%{release}

%description lib
lib components for the R-sna package.


%package license
Summary: license components for the R-sna package.
Group: Default

%description license
license components for the R-sna package.


%prep
%setup -q -n sna
cd %{_builddir}/sna

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1678832730

%install
export SOURCE_DATE_EPOCH=1678832730
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-sna
cp %{_builddir}/sna/COPYING %{buildroot}/usr/share/package-licenses/R-sna/2c4c203a956f9c8235dd0a698f6cdac4ab435290 || :
export LANG=C.UTF-8
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$FFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/sna/DESCRIPTION
/usr/lib64/R/library/sna/INDEX
/usr/lib64/R/library/sna/Meta/Rd.rds
/usr/lib64/R/library/sna/Meta/data.rds
/usr/lib64/R/library/sna/Meta/features.rds
/usr/lib64/R/library/sna/Meta/hsearch.rds
/usr/lib64/R/library/sna/Meta/links.rds
/usr/lib64/R/library/sna/Meta/nsInfo.rds
/usr/lib64/R/library/sna/Meta/package.rds
/usr/lib64/R/library/sna/NAMESPACE
/usr/lib64/R/library/sna/R/sna
/usr/lib64/R/library/sna/R/sna.rdb
/usr/lib64/R/library/sna/R/sna.rdx
/usr/lib64/R/library/sna/data/coleman.RData
/usr/lib64/R/library/sna/help/AnIndex
/usr/lib64/R/library/sna/help/aliases.rds
/usr/lib64/R/library/sna/help/paths.rds
/usr/lib64/R/library/sna/help/sna.rdb
/usr/lib64/R/library/sna/help/sna.rdx
/usr/lib64/R/library/sna/html/00Index.html
/usr/lib64/R/library/sna/html/R.css

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/sna/libs/sna.so
/usr/lib64/R/library/sna/libs/sna.so.avx2
/usr/lib64/R/library/sna/libs/sna.so.avx512

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-sna/2c4c203a956f9c8235dd0a698f6cdac4ab435290
